### PR TITLE
Added support for Image in the Heatmap class.  This assumes a grayscale image, but will take the value from HSV to use for intensity if a color image is provided.  The heatmap class could be refactored to show the raw image, preserving the color.  But this is a problem for another day.  Potentially closes #3870

### LINKED ISSUE #3870: Image: new plot type for displaying image files
Make it easy to display bitmaps, png files, etc. loaded either from disk or from memory

spillover from #3866

### PR DESCRIPTION
**Pull request by sdpenner**
Added Image support to the Heatmap class.  Provided images are expected to be grayscale.  Color images are implicitly converted to grayscale to derive the intensities array.  Potentially closes #3870, unless raw image display is desired.

### CODE REVIEW

**Comment by swharden** [comment]
Hi @sdpenner, I wanted to indicate that I see this pull request! It looks like it was made into your private repository (sdpenner/ScottPlot) not the ScottPlot repository (ScottPlot/ScottPlot) so I can't merge it into the main project. 

That's okay though! I can see the code changes here and I'll adapt some of what I see to create a new `Image` plot type (instead of trying to extend the heatmap plot type to add image functionality) 👍

**Comment by swharden** [comment]
I created https://github.com/ScottPlot/ScottPlot/commit/5e3461a600b4a6b79adb36c89fa4bb307609e3e1 and merged it in. It will be in the next release along with a cookbook example. Take a look when it comes out and if it doesn't meet all the goals of this pull request, let me know and we can create a new issue to track adding new features!

Thanks again for this pull request 😄

**Comment by sdpenner** [comment]
That all sounds great. Glad you found it useful. 
    -Scott
  

 From: Scott W Harden ***@***.***>Sent: Friday, June 7, 2024 6:29 PMTo: sdpenner/ScottPlot ***@***.***>Cc: sdpenner ***@***.***>; Mention ***@***.***>Subject: Re: [sdpenner/ScottPlot] Added support for Image in the Heatmap class. This assumes a grayscale image, but will take the value from HSV to use for intensity if a color image is provided. The heatmap class could be refactored to show the raw image, preserving the color. But this is a problem for another day. Potentially closes #3870 (PR #1) 
I created ***@***.*** and merged it in. It will be in the next release along with a cookbook example. Take a look when it comes out and if it doesn't meet all the goals of this pull request, let me know and we can create a new issue to track adding new features!
Thanks again for this pull request 😄

**Comment by sdpenner** [comment]
I keep asking myself to pull this?!  Not sure how to do this properly from VS.

**Pull request closed without merging**
